# Generated by Django 3.2.7 on 2021-10-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchTab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.CharField(default=1, max_length=1000, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
